image:
  file: gitpod.Dockerfile
tasks:
  - name: tailscaled
    command: |
      sudo tailscaled
  - name: tailscale
    command: |
      sudo -E tailscale up --hostname "gitpod-tailscale-demo" \
                           --authkey "${TAILSCALE_AUTHKEY}"

experimentalNetwork: true
